//TODO: Implementar
//TODO: Testar
package st.tipologia;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 * Formulário para manutenção (inserção e exclusão) dos componentes e tipologias
 * @author SCS214
 */
public class FormMantedor extends javax.swing.JFrame {
    
    ControleTipologia cTip = new ControleTipologia();
    
    /**
     * Creates new form FormMantedor
     */
    public FormMantedor() {
        initComponents();
        preencherCComponente();
        preencherTComponente();
        preencherTTipologia();
        
        itemComponenteMouseClicked(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelComponente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCNome = new javax.swing.JTextField();
        txtCAltura = new javax.swing.JTextField();
        txtCLargura = new javax.swing.JTextField();
        txtCMassa = new javax.swing.JTextField();
        txtCPreco = new javax.swing.JTextField();
        btnCAdicionar = new javax.swing.JButton();
        btnCExcluir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCComponente = new javax.swing.JTable();
        cmbCTipo = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        spiCFogo = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        spiCSom = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        spiCMeca = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        spiCUmi = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        painelTipologia = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtTAltura = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTLargura = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTPreco = new javax.swing.JTextField();
        btnTAdicionar = new javax.swing.JButton();
        btnTExcluir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTTipologia = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTComponente = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        spiTSom = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        spiTMeca = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        spiTUmi = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        spiTFogo = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        menuMantedor = new javax.swing.JMenuBar();
        itemComponente = new javax.swing.JMenu();
        itemTipologia = new javax.swing.JMenu();

        setTitle("Registro de Materiais");

        jLabel1.setText("Nome descritivo:");

        jLabel2.setText("Altura (cm):");

        jLabel3.setText("Largura (cm):");

        jLabel4.setText("Massa (g):");

        jLabel5.setText("Preço (R$):");

        btnCAdicionar.setText("Adicionar");
        btnCAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCAdicionarActionPerformed(evt);
            }
        });

        btnCExcluir.setText("Excluir");
        btnCExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCExcluirActionPerformed(evt);
            }
        });

        jLabel9.setText("Selecione um componente:");

        tblCComponente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCComponente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCComponenteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCComponente);

        cmbCTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CHAPA", "FORRO", "PARAFUSO" }));

        jLabel12.setText("Tipo:");

        jLabel13.setText("Fator fogo:");

        jLabel14.setText("Fator som:");

        jLabel15.setText("Fator umidade:");

        jLabel16.setText("Fator mecânico:");

        javax.swing.GroupLayout painelComponenteLayout = new javax.swing.GroupLayout(painelComponente);
        painelComponente.setLayout(painelComponenteLayout);
        painelComponenteLayout.setHorizontalGroup(
            painelComponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelComponenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelComponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelComponenteLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelComponenteLayout.createSequentialGroup()
                        .addGroup(painelComponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelComponenteLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCNome, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelComponenteLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(painelComponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(painelComponenteLayout.createSequentialGroup()
                                        .addGroup(painelComponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(painelComponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(painelComponenteLayout.createSequentialGroup()
                                                .addComponent(cmbCTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(36, 36, 36)
                                                .addComponent(jLabel13))
                                            .addGroup(painelComponenteLayout.createSequentialGroup()
                                                .addComponent(txtCAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(98, 98, 98))
                                            .addComponent(jLabel3)
                                            .addGroup(painelComponenteLayout.createSequentialGroup()
                                                .addComponent(txtCMassa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(36, 36, 36)
                                                .addComponent(jLabel5))))
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelComponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelComponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCLargura)
                                        .addComponent(txtCPreco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(painelComponenteLayout.createSequentialGroup()
                                        .addGroup(painelComponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(spiCFogo, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                            .addComponent(spiCUmi))
                                        .addGroup(painelComponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(painelComponenteLayout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(spiCSom))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelComponenteLayout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(spiCMeca, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(23, 23, 23)
                        .addGroup(painelComponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(painelComponenteLayout.createSequentialGroup()
                        .addGroup(painelComponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        painelComponenteLayout.setVerticalGroup(
            painelComponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelComponenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelComponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCAdicionar)
                    .addGroup(painelComponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtCNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(painelComponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtCLargura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnCExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(painelComponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCMassa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtCPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(painelComponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelComponenteLayout.createSequentialGroup()
                        .addGroup(painelComponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(spiCFogo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(painelComponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spiCUmi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(painelComponenteLayout.createSequentialGroup()
                        .addGroup(painelComponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(spiCSom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(painelComponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spiCMeca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))))
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel6.setText("Altura (cm):");

        jLabel7.setText("Largura (cm):");

        jLabel8.setText("Preço (R$):");

        btnTAdicionar.setText("Adicionar");
        btnTAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTAdicionarActionPerformed(evt);
            }
        });

        btnTExcluir.setText("Excluir");
        btnTExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTExcluirActionPerformed(evt);
            }
        });

        tblTTipologia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTTipologia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTTipologiaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTTipologia);

        jLabel10.setText("Selecione os componentes para adicionar à tipologia:");

        tblTComponente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblTComponente);

        jLabel11.setText("Selecione a tipologia:");

        jLabel17.setText("Fator som:");

        jLabel18.setText("Fator umidade:");

        jLabel19.setText("Fator mecânico:");

        jLabel20.setText("Fator fogo:");

        javax.swing.GroupLayout painelTipologiaLayout = new javax.swing.GroupLayout(painelTipologia);
        painelTipologia.setLayout(painelTipologiaLayout);
        painelTipologiaLayout.setHorizontalGroup(
            painelTipologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTipologiaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelTipologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTipologiaLayout.createSequentialGroup()
                        .addGroup(painelTipologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelTipologiaLayout.createSequentialGroup()
                                .addGroup(painelTipologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelTipologiaLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(painelTipologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(painelTipologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTLargura, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(painelTipologiaLayout.createSequentialGroup()
                                        .addGap(288, 288, 288)
                                        .addGroup(painelTipologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel18))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(painelTipologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(spiTFogo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spiTUmi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(9, 9, 9)
                                        .addGroup(painelTipologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(painelTipologiaLayout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(spiTSom, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTipologiaLayout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(spiTMeca, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(30, 30, 30)
                                .addGroup(painelTipologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 50, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(painelTipologiaLayout.createSequentialGroup()
                        .addGroup(painelTipologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        painelTipologiaLayout.setVerticalGroup(
            painelTipologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTipologiaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelTipologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelTipologiaLayout.createSequentialGroup()
                        .addGroup(painelTipologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(txtTLargura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(painelTipologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(spiTFogo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spiTSom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(painelTipologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spiTUmi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spiTMeca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelTipologiaLayout.createSequentialGroup()
                        .addComponent(btnTAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTExcluir)
                        .addGap(87, 87, 87)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        itemComponente.setText("Componente");
        itemComponente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemComponenteMouseClicked(evt);
            }
        });
        menuMantedor.add(itemComponente);

        itemTipologia.setText("Tipologia");
        itemTipologia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemTipologiaMouseClicked(evt);
            }
        });
        menuMantedor.add(itemTipologia);

        setJMenuBar(menuMantedor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelComponente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelTipologia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelComponente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelTipologia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemComponenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemComponenteMouseClicked
        painelComponente.setVisible(true);
        painelTipologia.setVisible(false);
    }//GEN-LAST:event_itemComponenteMouseClicked

    private void itemTipologiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemTipologiaMouseClicked
        painelComponente.setVisible(false);
        painelTipologia.setVisible(true);
    }//GEN-LAST:event_itemTipologiaMouseClicked

    private void btnCAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCAdicionarActionPerformed
        inserirComponente();
        preencherCComponente();
        preencherTComponente();
        preencherTTipologia();
    }//GEN-LAST:event_btnCAdicionarActionPerformed

    private void btnCExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCExcluirActionPerformed
        excluirComponente();
        preencherCComponente();
        preencherTComponente();
        preencherTTipologia();
    }//GEN-LAST:event_btnCExcluirActionPerformed

    private void btnTAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTAdicionarActionPerformed
        inserirTipologia();
        preencherCComponente();
        preencherTComponente();
        preencherTTipologia();
    }//GEN-LAST:event_btnTAdicionarActionPerformed

    private void btnTExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTExcluirActionPerformed
        excluirComponente();
        preencherCComponente();
        preencherTComponente();
        preencherTTipologia();
    }//GEN-LAST:event_btnTExcluirActionPerformed

    private void tblCComponenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCComponenteMouseClicked
        int linha = tblCComponente.getSelectedRow();
        if(linha < 0)
            return;
        
        txtCNome.setText(tblCComponente.getModel().getValueAt(linha, 0).toString());
        txtCAltura.setText(tblCComponente.getModel().getValueAt(linha, 1).toString());
        txtCLargura.setText(tblCComponente.getModel().getValueAt(linha, 2).toString());
        txtCMassa.setText(tblCComponente.getModel().getValueAt(linha, 3).toString());
        txtCPreco.setText(tblCComponente.getModel().getValueAt(linha, 4).toString());
        cmbCTipo.setSelectedItem(tblCComponente.getModel().getValueAt(linha, 5).toString());
        spiCFogo.setModel(new SpinnerNumberModel(Integer.parseInt(tblCComponente.getModel().getValueAt(linha, 6).toString()),0,100,1));
        spiCSom.setModel(new SpinnerNumberModel(Integer.parseInt(tblCComponente.getModel().getValueAt(linha, 7).toString()),0,100,1));
        spiCUmi.setModel(new SpinnerNumberModel(Integer.parseInt(tblCComponente.getModel().getValueAt(linha, 8).toString()),0,100,1));
        spiCMeca.setModel(new SpinnerNumberModel(Integer.parseInt(tblCComponente.getModel().getValueAt(linha, 9).toString()),0,100,1));
    }//GEN-LAST:event_tblCComponenteMouseClicked

    private void tblTTipologiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTTipologiaMouseClicked
        int linha = tblTTipologia.getSelectedRow();
        if(linha < 0)
            return;
        
        txtTAltura.setText(tblTTipologia.getModel().getValueAt(linha, 0).toString());
        txtTLargura.setText(tblTTipologia.getModel().getValueAt(linha, 1).toString());
        txtTPreco.setText(tblTTipologia.getModel().getValueAt(linha, 2).toString());
        spiTFogo.setModel(new SpinnerNumberModel(Integer.parseInt(tblTTipologia.getModel().getValueAt(linha, 3).toString()),0,100,1));;
        spiTSom.setModel(new SpinnerNumberModel(Integer.parseInt(tblTTipologia.getModel().getValueAt(linha, 4).toString()),0,100,1));;
        spiTUmi.setModel(new SpinnerNumberModel(Integer.parseInt(tblTTipologia.getModel().getValueAt(linha, 5).toString()),0,100,1));;
        spiTMeca.setModel(new SpinnerNumberModel(Integer.parseInt(tblTTipologia.getModel().getValueAt(linha, 6).toString()),0,100,1));;
        
        
        tblTComponente.setModel(new javax.swing.table.DefaultTableModel(
            cTip.verDetalhes(linha),
            new String [] {
                "Nome desc.", "Altura (cm)", "Largura (cm)", "Massa (g)", "Preço (R$)",
                "Tipo", "Fogo", "Som", "Umid.", "Mecan."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        
        tblTComponente.getColumnModel().getColumn(0).setMaxWidth(500);
        tblTComponente.getColumnModel().getColumn(1).setMaxWidth(120);
        tblTComponente.getColumnModel().getColumn(2).setMaxWidth(120);
        tblTComponente.getColumnModel().getColumn(3).setMaxWidth(120);
        tblTComponente.getColumnModel().getColumn(4).setMaxWidth(120);
        tblTComponente.getColumnModel().getColumn(5).setMaxWidth(200);
        tblTComponente.getColumnModel().getColumn(6).setMaxWidth(60);
        tblTComponente.getColumnModel().getColumn(7).setMaxWidth(60);
        tblTComponente.getColumnModel().getColumn(8).setMaxWidth(60);
        tblTComponente.getColumnModel().getColumn(9).setMaxWidth(60);
    }//GEN-LAST:event_tblTTipologiaMouseClicked
    
    private void preencherCComponente() {
        tblCComponente.setModel(new javax.swing.table.DefaultTableModel(
            cTip.verComponentes(),
            new String [] {
                "Nome desc.", "Altura (cm)", "Largura (cm)", "Massa (g)", "Preço (R$)",
                "Tipo", "Fogo", "Som", "Umid.", "Mecan."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        
        tblCComponente.getColumnModel().getColumn(0).setMaxWidth(500);
        tblCComponente.getColumnModel().getColumn(1).setMaxWidth(120);
        tblCComponente.getColumnModel().getColumn(2).setMaxWidth(120);
        tblCComponente.getColumnModel().getColumn(3).setMaxWidth(120);
        tblCComponente.getColumnModel().getColumn(4).setMaxWidth(120);
        tblCComponente.getColumnModel().getColumn(5).setMaxWidth(200);
        tblCComponente.getColumnModel().getColumn(6).setMaxWidth(60);
        tblCComponente.getColumnModel().getColumn(7).setMaxWidth(60);
        tblCComponente.getColumnModel().getColumn(8).setMaxWidth(60);
        tblCComponente.getColumnModel().getColumn(9).setMaxWidth(60);
    }
    
    private void preencherTComponente() {
        tblTComponente.setModel(new javax.swing.table.DefaultTableModel(
            null,
            new String [] {
                "Nome desc.", "Altura (cm)", "Largura (cm)", "Massa (g)", "Preço (R$)",
                "Tipo", "Fogo", "Som", "Umid.", "Mecan."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        
        tblTComponente.getColumnModel().getColumn(0).setMaxWidth(500);
        tblTComponente.getColumnModel().getColumn(1).setMaxWidth(120);
        tblTComponente.getColumnModel().getColumn(2).setMaxWidth(120);
        tblTComponente.getColumnModel().getColumn(3).setMaxWidth(120);
        tblTComponente.getColumnModel().getColumn(4).setMaxWidth(120);
        tblTComponente.getColumnModel().getColumn(5).setMaxWidth(200);
        tblTComponente.getColumnModel().getColumn(6).setMaxWidth(60);
        tblTComponente.getColumnModel().getColumn(7).setMaxWidth(60);
        tblTComponente.getColumnModel().getColumn(8).setMaxWidth(60);
        tblTComponente.getColumnModel().getColumn(9).setMaxWidth(60);
    }
    
    private void preencherTTipologia() {
        tblTTipologia.setModel(new javax.swing.table.DefaultTableModel(
            cTip.verTipologias(),
            new String [] {
                "Altura (cm)", "Largura (cm)", "Preço (R$)", "Fogo", "Som", "Umid.", "Mecan."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        
        tblTTipologia.getColumnModel().getColumn(0).setMaxWidth(200);
        tblTTipologia.getColumnModel().getColumn(1).setMaxWidth(200);
        tblTTipologia.getColumnModel().getColumn(2).setMaxWidth(200);
        tblTTipologia.getColumnModel().getColumn(3).setMaxWidth(60);
        tblTTipologia.getColumnModel().getColumn(4).setMaxWidth(60);
        tblTTipologia.getColumnModel().getColumn(5).setMaxWidth(60);
        tblTTipologia.getColumnModel().getColumn(6).setMaxWidth(60);
    }
    
    /**
     * Exibe uma caixa de mensagem
     * @param msg Mensagem a ser exibida
     */
    public void exibirMensagem(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }
    /**
     * Insere um componente
     */
    public void inserirComponente() {
        if(!validarCCampos())
            return;
        
        try {
            Componente c = new Componente();
            c.setNome(txtCNome.getText());
            c.setAltura(Float.parseFloat(txtCAltura.getText()));
            c.setLargura(Float.parseFloat(txtCLargura.getText()));
            c.setMassa(Float.parseFloat(txtCMassa.getText()));
            c.setPreco(Float.parseFloat(txtCPreco.getText()));
            c.setTipo(Componente.Tipo.valueOf(cmbCTipo.getSelectedItem().toString()));

            Ambiente a = new Ambiente();
            a.setFatorFogo(Integer.parseInt(spiCFogo.getValue().toString()));
            a.setFatorSom(Integer.parseInt(spiCSom.getValue().toString()));
            a.setFatorUmidade(Integer.parseInt(spiCUmi.getValue().toString()));
            a.setFatorMecanico(Integer.parseInt(spiCMeca.getValue().toString()));
            c.setAmbiente(a);
            
            ControleMantedor cm = new ControleMantedor();
            cm.inserirComponente(c);
        } catch(Exception ex) {
            exibirMensagem("Os dados não foram inseridos corretamente.");
        }
    }
    /**
     * Exclui um componente
     */
    public void excluirComponente() {
        if(!validarCCampos())
            return;
        
        try {
            Componente c = new Componente();
            c.setNome(txtCNome.getText());
            c.setAltura(Float.parseFloat(txtCAltura.getText()));
            c.setLargura(Float.parseFloat(txtCLargura.getText()));
            c.setMassa(Float.parseFloat(txtCMassa.getText()));
            c.setPreco(Float.parseFloat(txtCPreco.getText()));
            c.setTipo(Componente.Tipo.valueOf(cmbCTipo.getSelectedItem().toString()));

            Ambiente a = new Ambiente();
            a.setFatorFogo(Integer.parseInt(spiCFogo.getValue().toString()));
            a.setFatorSom(Integer.parseInt(spiCSom.getValue().toString()));
            a.setFatorUmidade(Integer.parseInt(spiCUmi.getValue().toString()));
            a.setFatorMecanico(Integer.parseInt(spiCMeca.getValue().toString()));
            c.setAmbiente(a);
            
            ControleMantedor cm = new ControleMantedor();
            cm.excluirComponente(c);
        } catch(Exception ex) {
            exibirMensagem("Os dados não foram inseridos corretamente.");
        }
    }
    /**
     * Insere uma tipologia
     */
    public void inserirTipologia() {
        if(!validarTCampos())
            return;
        
        try {
            Tipologia t = new Tipologia();
            t.setAltura(Float.parseFloat(txtTAltura.getText()));
            t.setLargura(Float.parseFloat(txtTLargura.getText()));
            t.setPreco(Float.parseFloat(txtTPreco.getText()));
            
            Ambiente am = new Ambiente();
            am.setFatorFogo(Integer.parseInt(spiTFogo.getValue().toString()));
            am.setFatorSom(Integer.parseInt(spiTSom.getValue().toString()));
            am.setFatorUmidade(Integer.parseInt(spiTUmi.getValue().toString()));
            am.setFatorMecanico(Integer.parseInt(spiTMeca.getValue().toString()));
            t.setAmbiente(am);
            
            List<Componente> comps = new ArrayList<>();
            for(int i: tblTComponente.getSelectedRows()) {
                Componente c = new Componente();
                c.setNome(tblTComponente.getModel().getValueAt(i, 0).toString());
                c.setAltura(Float.parseFloat(tblTComponente.getModel().getValueAt(i, 1).toString()));
                c.setLargura(Float.parseFloat(tblTComponente.getModel().getValueAt(i, 2).toString()));
                c.setMassa(Float.parseFloat(tblTComponente.getModel().getValueAt(i, 3).toString()));
                c.setPreco(Float.parseFloat(tblTComponente.getModel().getValueAt(i, 4).toString()));
                c.setTipo(Componente.Tipo.valueOf(tblTComponente.getModel().getValueAt(i, 5).toString()));

                Ambiente a = new Ambiente();
                a.setFatorFogo(Integer.parseInt(tblTComponente.getModel().getValueAt(i, 6).toString()));
                a.setFatorSom(Integer.parseInt(tblTComponente.getModel().getValueAt(i, 7).toString()));
                a.setFatorUmidade(Integer.parseInt(tblTComponente.getModel().getValueAt(i, 8).toString()));
                a.setFatorMecanico(Integer.parseInt(tblTComponente.getModel().getValueAt(i, 9).toString()));
                c.setAmbiente(a);

                comps.add(c);
            }
            t.setListaComponentes(comps);
            
            //TESTE
            /*System.out.println("Inserindo tipologia");
            System.out.println(t.getAltura());
            System.out.println(t.getLargura());
            System.out.println(t.getPreco());
            System.out.println(t.getAmbiente().getFatorFogo());
            System.out.println(t.getAmbiente().getFatorSom());
            System.out.println(t.getAmbiente().getFatorUmidade());
            System.out.println(t.getAmbiente().getFatorMecanico());*/
            //TESTE
            
            ControleMantedor cm = new ControleMantedor();
            cm.inserirTipologia(t);
        } catch(Exception ex) {
            exibirMensagem("Os dados não foram inseridos corretamente.");
        }
    }
    /**
     * Exclui uma tipologia
     */
    public void excluirTipologia() {
        if(!validarTCampos())
            return;
        
        try {
            Tipologia t = new Tipologia();
            t.setAltura(Float.parseFloat(txtTAltura.getText()));
            t.setLargura(Float.parseFloat(txtTLargura.getText()));
            t.setPreco(Float.parseFloat(txtTPreco.getText()));
            
            Ambiente am = new Ambiente();
            am.setFatorFogo(Integer.parseInt(spiTFogo.getValue().toString()));
            am.setFatorSom(Integer.parseInt(spiTSom.getValue().toString()));
            am.setFatorUmidade(Integer.parseInt(spiTUmi.getValue().toString()));
            am.setFatorMecanico(Integer.parseInt(spiTMeca.getValue().toString()));
            t.setAmbiente(am);
            
            List<Componente> comps = new ArrayList<>();
            for(int i: tblTComponente.getSelectedRows()) {
                Componente c = new Componente();
                c.setNome(tblTComponente.getModel().getValueAt(i, 0).toString());
                c.setAltura(Float.parseFloat(tblTComponente.getModel().getValueAt(i, 1).toString()));
                c.setLargura(Float.parseFloat(tblTComponente.getModel().getValueAt(i, 2).toString()));
                c.setMassa(Float.parseFloat(tblTComponente.getModel().getValueAt(i, 3).toString()));
                c.setPreco(Float.parseFloat(tblTComponente.getModel().getValueAt(i, 4).toString()));
                c.setTipo(Componente.Tipo.valueOf(tblTComponente.getModel().getValueAt(i, 5).toString()));

                Ambiente a = new Ambiente();
                a.setFatorFogo(Integer.parseInt(tblTComponente.getModel().getValueAt(i, 6).toString()));
                a.setFatorSom(Integer.parseInt(tblTComponente.getModel().getValueAt(i, 7).toString()));
                a.setFatorUmidade(Integer.parseInt(tblTComponente.getModel().getValueAt(i, 8).toString()));
                a.setFatorMecanico(Integer.parseInt(tblTComponente.getModel().getValueAt(i, 9).toString()));
                c.setAmbiente(a);

                comps.add(c);
            }
            t.setListaComponentes(comps);
            
            ControleMantedor cm = new ControleMantedor();
            cm.excluirTipologia(t);
        } catch(Exception ex) {
            exibirMensagem("Os dados não foram inseridos corretamente.");
        }
    }
    
    public boolean validarCCampos() {
        return(
                !"".equals(txtCNome.getText()) &&
                !"".equals(txtCAltura.getText()) &&
                !"".equals(txtCLargura.getText()) &&
                !"".equals(txtCMassa.getText()) &&
                !"".equals(txtCPreco.getText()) &&
                !"".equals(cmbCTipo.getSelectedItem().toString()) &&
                !"".equals(spiCFogo.getValue().toString()) &&
                !"".equals(spiCSom.getValue().toString()) &&
                !"".equals(spiCUmi.getValue().toString()) &&
                !"".equals(spiCMeca.getValue().toString())
                );
    }
    
    public boolean validarTCampos() {
        return(
                !"".equals(txtTAltura.getText()) &&
                !"".equals(txtTLargura.getText()) &&
                !"".equals(txtTPreco.getText()) &&
                !"".equals(spiTFogo.getValue().toString()) &&
                !"".equals(spiTSom.getValue().toString()) &&
                !"".equals(spiTUmi.getValue().toString()) &&
                !"".equals(spiTMeca.getValue().toString())
                );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCAdicionar;
    private javax.swing.JButton btnCExcluir;
    private javax.swing.JButton btnTAdicionar;
    private javax.swing.JButton btnTExcluir;
    private javax.swing.JComboBox cmbCTipo;
    private javax.swing.JMenu itemComponente;
    private javax.swing.JMenu itemTipologia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenuBar menuMantedor;
    private javax.swing.JPanel painelComponente;
    private javax.swing.JPanel painelTipologia;
    private javax.swing.JSpinner spiCFogo;
    private javax.swing.JSpinner spiCMeca;
    private javax.swing.JSpinner spiCSom;
    private javax.swing.JSpinner spiCUmi;
    private javax.swing.JSpinner spiTFogo;
    private javax.swing.JSpinner spiTMeca;
    private javax.swing.JSpinner spiTSom;
    private javax.swing.JSpinner spiTUmi;
    private javax.swing.JTable tblCComponente;
    private javax.swing.JTable tblTComponente;
    private javax.swing.JTable tblTTipologia;
    private javax.swing.JTextField txtCAltura;
    private javax.swing.JTextField txtCLargura;
    private javax.swing.JTextField txtCMassa;
    private javax.swing.JTextField txtCNome;
    private javax.swing.JTextField txtCPreco;
    private javax.swing.JTextField txtTAltura;
    private javax.swing.JTextField txtTLargura;
    private javax.swing.JTextField txtTPreco;
    // End of variables declaration//GEN-END:variables
}
